### ISSUE TITLE
Pending updates... Can we merge them?

### ISSUE THREAD

**Issue by cougar97536** [Triskelia/Bambi-Dumbtalk-Script#3]
**Issue description**
Just found your script and like totes love it.  I like see that someone submitted a bunch of tweaks last year and they are still like pending.  Any way you could review them and release them?  I think others would totally use this if it had a bit of support... the comunity is pretty busy now if you haven't been on in a while.

Please make use of the labels (you can assign them on the right ==>)

**Comment by Triskelia** [comment]
Hello,

I wasn't able to merge the changes from that pull request.
It changed a lot of things, and removed the bambi stuff completely.
And since I was planning a major refactoring anyway, it wouldn't have made a lot of sense.

I did however manually add most of the new features suggested for 1.0
