### ISSUE TITLE
How to uninstall/stop program from running?

### ISSUE THREAD

**Issue by stormthecastle13** [Triskelia/Bambi-Dumbtalk-Script#7]
I am trying to delete this program, but it won't let me delete it or the folder because it is still running in script. I'm not adept in computer science, but I desperately want the folder fully off my computer. Any help is appreciated.

**Comment by Triskelia** [comment]
Hello,
You can stop the program by extending the tray bar in the right of your task bar. You should see a little icon, of a brain and speech bubble" there (or a green "H" button, depending on the version). Just need to right click, then on "Exit".
You should then be able to delete the folder.

Another solution would be to just restart your computer. The folder should then be removable.

Hope it helps
